include theos/makefiles/common.mk

TWEAK_NAME = LithiumServer
LithiumServer_FILES = Server.m
LithiumServer_FRAMEWORKS = UIKit Foundation CoreGraphics
LithiumServer_LIBRARIES = objcipc
LithiumServer_LDFLAGS += -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/tweak.mk